query getProductsByCategory($uid: String) {
  products(filter: { category_uid: { eq: $uid } }) {
    total_count
    items {
      name
      sku
      image {
        url
        label
      }
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
    }
    page_info {
      page_size
      current_page
    }
  }
}
